### ISSUE TITLE
the stealth check macro gives an error

### ISSUE THREAD

**Issue by juicyblox** [foundry-vtt-community/macros#23] opened 2020-05-08 09:44 UTC
I am using furnace with advanced scripts.  I am not good at reading console, sorry.

**Comment by AnthonyVadala** [comment] 2020-05-08 11:56
Tagging in @shawndibble to see if they can help you out.

**Comment by shawndibble** [comment] 2020-05-08 20:06
How are you using the macro? You need to select a token linked to an actor and then run the macro. Or you need to be assigned a token linked to an actor to your logged in account (player with token assigned).

https://streamable.com/5ih42g

If you are getting an error, can your paste a screenshot of the console error?

**Comment by juicyblox** [comment] 2020-05-08 20:37
I do the same as you show.  Here is what my console says...
[https://imgur.com/UoJCLeD](url)

Perhaps there is a mod conflict with any of these?
Actually private rolls
Alt 5e sheet
Better rolls
CUB
compendium browser
deselection
encounter builder
furnace
image previewer
itemcollection
item delete check
lootsheetnpc5e
mountup
pin-cushion
pings
vtta dndbeyond
vtta iconizer
vtta tokenizer

**Comment by shawndibble** [comment] 2020-05-08 20:42
Try this code out, and send back the console. The issue is that name can't be found. There are 3 things that is looking for name, so I need to know which is breaking.

`// getting all actors of selected tokens
let actors = canvas.tokens.controlledTokens.map(({ actor }) => actor);

// if there are no selected tokens, roll for the player's character.
if (actors.length < 1) {
  actors = game.users.entities.map(entity => {
    if (entity.active && entity.character !== null) {
      return entity.character;
    }
  });
}
const validActors = actors.filter(actor => actor != null);

let messageContent = 'pp = passive perception<br>';

// roll for every actor
for (const selectedActor of validActors) {
  const stealthMod = selectedActor.data.data.skills.ste.mod; 
  const stealth = new Roll(`1d20+${stealthMod}`).roll().total; 
  console.log('selectedActor', selectedActor);
  messageContent += `<hr><h3>${selectedActor.name} stealth roll was a <b>${stealth}</b>.</h3>`;

  // grab a list of unique tokens then check their passive perception against the rolled stealth.
  const uniqueActor = {};
  const caughtBy = canvas.tokens.placeables
    .filter((token) => { // filter out duplicate token names. ie: we assume all goblins have the same passive perception
    console.log('token.actor', token.actor);
      if (uniqueActor[token.actor.name]) {
        return false;
      }
      uniqueActor[token.actor.name] = true;
      return true;
    })
    .filter(token => {
      return selectedActor.id !== token.actor.id; // Don't check to see if the token sees himself.
    })
    .filter(({ actor }) => actor.data.data.skills.prc.passive >= stealth); // check map tokens passives with roller stealth

  if (!caughtBy.length) {
    messageContent += 'Stealth successful!<br>';
  } else {
    messageContent += 'Stealth questionable:<br>';
    caughtBy.map(({ actor }) => {
    console.log('actor', actor);
      messageContent += `<b>${actor.name}</b> pp(${actor.data.data.skills.prc.passive}).<br>`;
    });
  }
}

// create the message
const chatData = {
  user: game.user._id,
  speaker: game.user,
  content: messageContent,
  whisper: game.users.entities.filter((u) => u.isGM).map((u) => u._id),
};
ChatMessage.create(chatData, {});`

**Comment by juicyblox** [comment] 2020-05-08 20:51
Sure.  Does every actor in game have to be linked to a player despite only selecting actors that I know are linked?

https://imgur.com/wmOWzlJ

**Comment by shawndibble** [comment] 2020-05-08 20:54
Yes, each token needs to be linked to an actor as it checks all tokens on the map to see if anyone might have seen the character. Usually making non actor tokens a tile instead would be enough to handle this, but I can have it ignore tokens that are not linked to an actor.

**Comment by shawndibble** [comment] 2020-05-08 20:55
Let me know if this fixes the issue. If so, I will make a PR.

```javascript
// getting all actors of selected tokens
let actors = canvas.tokens.controlledTokens.map(({ actor }) => actor);

// if there are no selected tokens, roll for the player's character.
if (actors.length < 1) {
  actors = game.users.entities.map(entity => {
    if (entity.active && entity.character !== null) {
      return entity.character;
    }
  });
}
const validActors = actors.filter(actor => actor != null);

let messageContent = 'pp = passive perception<br>';

// roll for every actor
for (const selectedActor of validActors) {
  const stealthMod = selectedActor.data.data.skills.ste.mod; 
  const stealth = new Roll(`1d20+${stealthMod}`).roll().total; 
  messageContent += `<hr><h3>${selectedActor.name} stealth roll was a <b>${stealth}</b>.</h3>`;

  // grab a list of unique tokens then check their passive perception against the rolled stealth.
  const uniqueActor = {};
  const caughtBy = canvas.tokens.placeables
    .filter((token) => { // filter out duplicate token names. ie: we assume all goblins have the same passive perception
      if (!token.actor || uniqueActor[token.actor.name]) {
        return false;
      }
      uniqueActor[token.actor.name] = true;
      return true;
    })
    .filter(token => {
      return selectedActor.id !== token.actor.id; // Don't check to see if the token sees himself.
    })
    .filter(({ actor }) => actor.data.data.skills.prc.passive >= stealth); // check map tokens passives with roller stealth

  if (!caughtBy.length) {
    messageContent += 'Stealth successful!<br>';
  } else {
    messageContent += 'Stealth questionable:<br>';
    caughtBy.map(({ actor }) => {
      messageContent += `<b>${actor.name}</b> pp(${actor.data.data.skills.prc.passive}).<br>`;
    });
  }
}

// create the message
const chatData = {
  user: game.user._id,
  speaker: game.user,
  content: messageContent,
  whisper: game.users.entities.filter((u) => u.isGM).map((u) => u._id),
};
ChatMessage.create(chatData, {});
```

**Comment by juicyblox** [comment] 2020-05-08 21:01
Nice, it's working!  Ty.  And just to clarify what I was saying, I tried with only two linked tokens on the scene with the old one.  Either way, it works now and it's much appreciated.

**Comment by juicyblox** [comment] 2020-05-08 21:08
You know what it could have been that I just noticed.  I had an unused journal entry on the map.

**Comment by shawndibble** [comment] 2020-05-08 21:17
I don't think it would have been a journal entry unless it was flagged as a token. All my maps have journal entries all over with no issues.

**Comment by AnthonyVadala** [comment] 2020-05-09 05:23
#24 has been merged.

Going to go ahead and resolve this issue.

**Closed by AnthonyVadala** 2020-05-09 05:23 UTC
Labels: bug
